Repository suitenumerique/people, pull requests merged in 2024-12, with the labels that each got.

#574 🔧(helm) fix siret validator for staging
  src/helm/env.d/staging/values.desk.yaml.gotmpl
Labels: noChangeLog

#581 ✅(e2e) sync keycloak users w/ backend users
  docker/auth/realm.json
  docs/testsE2E.md
  src/backend/demo/management/commands/create_demo.py
  src/frontend/apps/e2e/__tests__/app-desk/common.ts
  src/frontend/apps/e2e/__tests__/app-desk/member-delete.spec.ts
Labels: noChangeLog, CI

#580 📝(contacts) update documentation
  docs/models.md
Labels: documentation, noChangeLog

#587 🐛(dimail) fix dimail setup command
  src/backend/mailbox_manager/management/commands/setup_dimail_db.py
Labels: noChangeLog

#595 🐛(backend) fix manage roles on domain admin view
  CHANGELOG.md
  src/backend/mailbox_manager/admin.py
Labels: noChangeLog

#588 💄(frontend) redirect home according to abilities
  CHANGELOG.md
  src/frontend/apps/desk/src/__tests__/pages.test.tsx
  src/frontend/apps/desk/src/pages/index.tsx
  src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts
  src/frontend/apps/e2e/__tests__/app-desk/mail-domains.spec.ts
Labels: frontend

#586 📝(tilt) add startup guide to Tilt use
  bin/start-kind.sh
  docs/local_development_kube.md
Labels: documentation, noChangeLog

#600 ✅(e2e) fix flaky test
  src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts
Labels: noChangeLog, test-e2e

#603 ⬆️(dimail) upgrade dimail to 0.0.20
  docker-compose.yml
Labels: noChangeLog

#598 🚚(backend) split users test file to improve readability
  src/backend/core/tests/users/__init__.py
  src/backend/core/tests/users/test_api_users_create.py
  src/backend/core/tests/users/test_api_users_delete.py
  src/backend/core/tests/users/test_api_users_list.py
  src/backend/core/tests/users/test_api_users_retrieve.py
  src/backend/core/tests/users/test_api_users_update.py
Labels: noChangeLog

#608 ⬆️(dimail) upgrade dimail to v0.1.1
  docker-compose.yml
  src/backend/mailbox_manager/api/client/serializers.py
Labels: noChangeLog

#611 🧑‍💻(user) fix the `User.language`
  CHANGELOG.md
  src/backend/core/migrations/0001_initial.py
  src/backend/core/models.py
Labels: noChangeLog, backend

#614 📝(scripts) add missing release instructions
  scripts/release.py
Labels: noChangeLog

#534 🐛(mailboxes) fix logic when attempting to duplicate mailboxes
  src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
  src/backend/mailbox_manager/utils/dimail.py
Labels: noChangeLog, backend
