Repository suitenumerique/people, pull requests merged in 2024-08, with the labels that each got.

#317 ✨(models) Test debug ci
  .github/workflows/people.yml
Labels: CI

#311 🚚(api) move swagger under /api/
  src/backend/core/tests/swagger/test_openapi_schema.py
  src/backend/people/urls.py
Labels: documentation, noChangeLog, backend, easy pick

#321 ✨ (mail) manage mailboxes permissions
  src/backend/mailbox_manager/api/permissions.py
  src/backend/mailbox_manager/api/serializers.py
  src/backend/mailbox_manager/api/viewsets.py
  src/backend/mailbox_manager/models.py
  src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py
  src/backend/mailbox_manager/tests/test_api_mailboxes_create.py
  src/backend/mailbox_manager/tests/test_api_mailboxes_list.py
  src/backend/mailbox_manager/tests/test_models_maildomain.py
Labels: noChangeLog

#323 ✅(tests) improve tests for mailbox api
  src/backend/mailbox_manager/factories.py
  src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py
  src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
  src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_list.py
Labels: noChangeLog, backend, easy pick

#325 ✨(mail) add first_name and last_name for Mailbox
  src/backend/mailbox_manager/admin.py
  src/backend/mailbox_manager/api/serializers.py
  src/backend/mailbox_manager/factories.py
  src/backend/mailbox_manager/migrations/0008_mailbox_first_name_mailbox_last_name.py
  src/backend/mailbox_manager/migrations/0009_fill_mailbox_first_name_mailbox_last_name.py
  src/backend/mailbox_manager/migrations/0010_alter_mailbox_first_name_alter_mailbox_last_name.py
  src/backend/mailbox_manager/models.py
  src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
  src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_list.py
Labels: noChangeLog

#332 ✨(mail) add status on domain retrieve
  src/backend/mailbox_manager/api/serializers.py
  src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
  src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py
Labels: noChangeLog

#335 🔖(major) major release to 1.0.0
  CHANGELOG.md
  src/backend/pyproject.toml
  src/frontend/apps/desk/package.json
  src/frontend/apps/e2e/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-people/package.json
  src/frontend/packages/i18n/package.json
  src/helm/env.d/preprod/values.desk.yaml.gotmpl
  src/helm/env.d/production/values.desk.yaml.gotmpl
Labels: V1

#343 🔖(patch) patch release to 1.0.1
  CHANGELOG.md
  src/backend/pyproject.toml
  src/frontend/apps/desk/package.json
  src/frontend/apps/e2e/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-people/package.json
  src/frontend/packages/i18n/package.json
  src/helm/env.d/preprod/values.desk.yaml.gotmpl
  src/helm/env.d/production/values.desk.yaml.gotmpl
  src/mail/package.json
  src/tsclient/package.json
Labels: release

#353 Corrige un test en échec intermittent
  src/backend/core/tests/team_accesses/test_api_team_accesses_list.py
Labels: noChangeLog
