Repository suitenumerique/people, pull requests merged in 2024-11, with the labels that each got.

#474 ✅(tests) test dimail setup command
  Makefile
  src/backend/mailbox_manager/management/commands/setup_dimail_db.py
  src/backend/mailbox_manager/tests/test_command_dimail_setup_db.py
Labels: noChangeLog, backend, dimail

#453 ✨(dimail) synchronize mailboxes from dimail to our db
  CHANGELOG.md
  src/backend/mailbox_manager/admin.py
  src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
  src/backend/mailbox_manager/tests/test_utils_dimail_client.py
  src/backend/mailbox_manager/utils/dimail.py
Labels: backend

#519 Separate security scan for frontend too
  .github/workflows/docker-hub.yml
Labels: noChangeLog, CI

#531 🔥(terraform) remove legacy terraform references
  .gitignore
  bin/_config.sh
  bin/state
  bin/terraform
  docker-compose.yml
Labels: noChangeLog

#539 Pin dimail-api version to fix main branch
  docker-compose.yml
Labels: noChangeLog

#549 📝(scripts) improve command to do to release
  scripts/release.py
Labels: noChangeLog

#552 💄(admin) allow header color customization
  CHANGELOG.md
  src/backend/admin/__init__.py
  src/backend/admin/apps.py
  src/backend/admin/sites.py
  src/backend/admin/templates/admin/base_site.html
  src/backend/people/settings.py
  src/helm/env.d/production/values.desk.yaml.gotmpl
  src/helm/env.d/staging/values.desk.yaml.gotmpl
Labels: backend

#543 📝(docs) light doc about org & SP
  docs/organizations.md
  docs/serviceProviders.md
Labels: noChangeLog

#566 Change production endpoint
  src/helm/env.d/production/values.desk.yaml.gotmpl
Labels: noChangeLog

#568 Change dev endpoints
  src/helm/env.d/preprod/values.desk.yaml.gotmpl
  src/helm/env.d/staging/values.desk.yaml.gotmpl
Labels: noChangeLog
