Repository suitenumerique/people, pull requests merged in 2024-02, with the labels that each got.

#34 🎨(project) fixed minor code formatting issues in .sops.yaml
  .sops.yaml
Labels: noChangeLog

#41 ✏️(project) fix minor typos
  Makefile
  README.md
  gitlint/gitlint_emoji.py
  src/backend/core/models.py
  src/backend/core/tests/test_models_oidc_user_getter.py
  src/backend/demo/management/commands/createsuperuser.py
  src/backend/people/settings.py
Labels: enhancement, noChangeLog

#48 🩹(backend) enhance Django Admin for Team Slug
  src/backend/core/admin.py
  src/backend/core/models.py
Labels: noChangeLog

#58 🩹(backend) fix Django Admin UserAdmin page
  src/backend/core/admin.py
  src/backend/core/models.py
Labels: bug, good first issue, noChangeLog

#44 🗃️(model) create invitation model
  src/backend/core/admin.py
  src/backend/core/api/serializers.py
  src/backend/core/factories.py
  src/backend/core/migrations/0001_initial.py
  src/backend/core/models.py
  src/backend/core/tests/test_models_invitations.py
  src/backend/people/settings.py
Labels: noChangeLog, backend

#62 ✏️(project) fix minor typos
  README.md
  src/backend/core/models.py
  src/backend/core/tests/test_api_contacts.py
  src/backend/core/tests/test_models_contacts.py
  src/backend/core/tests/test_models_identities.py
  src/backend/core/tests/test_models_users.py
  src/backend/core/tokens.py
  src/backend/people/settings.py
Labels: noChangeLog, easy pick

#70 ✨(backend) remove users returning profile_contact
  src/backend/core/api/serializers.py
  src/backend/core/api/viewsets.py
  src/backend/core/migrations/0001_initial.py
  src/backend/core/models.py
  src/backend/core/tests/test_api_users.py
Labels: noChangeLog, backend

#53 🎨(frontend) Consistency url
  src/frontend/apps/desk/src/pages/index.tsx
  src/frontend/apps/desk/src/pages/teams/index.tsx
  src/frontend/apps/e2e/__tests__/app-desk/teams-create.spec.ts
Labels: frontend, noChangeLog
