Repository suitenumerique/people, pull requests merged in 2024-01, with the labels that each got.

#7 👷(ci) fix ci issue with changelog
  .github/workflows/people.yml
Labels: noChangeLog

#9 👷(ci) fix python linting
  .github/workflows/people.yml
Labels: noChangeLog

#8 👷(ci) fix ci issue with changelog
  .github/workflows/people.yml
Labels: noChangeLog

#11 ✅(app-desk) install jest
  .github/workflows/people.yml
  src/frontend/app/desk/.eslintrc.js
  src/frontend/app/desk/jest.config.ts
  src/frontend/app/desk/package.json
  src/frontend/app/desk/src/app/__tests__/page.test.tsx
  src/frontend/app/desk/yarn.lock
Labels: dependencies, frontend, noChangeLog, easy pick

#10 👷(ci) Configure workflows to use sops secrets instead of github secrets
  .github/workflows/people.yml
  .github/workflows/secrets.enc.env
  .sops.yaml
  scripts/install-pre-commit-hook.sh
Labels: noChangeLog

#16 ✨(api) search users by email
  src/backend/core/api/serializers.py
  src/backend/core/api/viewsets.py
  src/backend/core/tests/test_api_users.py
  src/backend/core/tests/test_throttle.py
  src/backend/people/settings.py
Labels: enhancement, noChangeLog, backend

#23 👷(ci) sops: Add age key
  .github/workflows/secrets.enc.env
  .sops.yaml
Labels: noChangeLog

#22 🔧(project) update Renovate configuration to fix match manager issue
  renovate.json
Labels: noChangeLog, easy pick

#24 👷(ci) sops: Add age key
  .github/workflows/secrets.enc.env
  .sops.yaml
Labels: noChangeLog

#28 🔧(project) enable renovate dependency dashboard
  renovate.json
Labels: noChangeLog
