Repository suitenumerique/people, pull requests merged in 2024-03, with the labels that each got.

#85 🤡(app-desk) remove mock accesses
  src/frontend/apps/desk/package.json
  src/frontend/apps/desk/src/features/teams/api/data/teams.ts
  src/frontend/apps/desk/src/features/teams/api/useTeamsAccesses.tsx
  src/frontend/apps/e2e/__tests__/app-desk/team.spec.ts
  src/frontend/yarn.lock
Labels: frontend, noChangeLog, easy pick

#98 🎨(backend) early return in User factory
  src/backend/core/factories.py
Labels: noChangeLog

#101 🌐(app-desk) translate role in member grid
  src/frontend/apps/desk/src/features/teams/__tests__/MemberGrid.test.tsx
  src/frontend/apps/desk/src/features/teams/components/Member/MemberGrid.tsx
  src/frontend/apps/e2e/__tests__/app-desk/team.spec.ts
Labels: frontend, noChangeLog, easy pick

#97 🩹(frontend) fix layout overflow in Team info
  src/frontend/apps/desk/src/features/teams/components/TeamInfo.tsx
Labels: enhancement, noChangeLog

#96 Enhance user search
  src/backend/core/api/viewsets.py
  src/backend/core/tests/test_api_users.py
Labels: enhancement, good first issue, noChangeLog, backend

#111 🐛(app-desk) close dropDown when click outside
  src/frontend/apps/desk/src/components/DropButton.tsx
Labels: frontend, noChangeLog, easy pick

#100 🧑‍💻(demo) improve distribution in number of identities per user
  src/backend/demo/defaults.py
  src/backend/demo/management/commands/create_demo.py
Labels: enhancement, noChangeLog, easy pick

#130 🔧(backend) configure RedisCache in production settings
  src/backend/people/settings.py
  src/backend/pyproject.toml
Labels: noChangeLog, backend

#133 🐛(docker) switch CMD form from Shell to Exec
  Dockerfile
Labels: noChangeLog, backend

#135 🌐(app-desk) order translations asc
  src/frontend/apps/desk/src/i18n/translations.json
  src/frontend/packages/i18n/format-deploy.mjs
Labels: frontend, noChangeLog, easy pick

#114 ✨(backend) convert invitations to accesses
  src/backend/core/models.py
  src/backend/core/tests/test_models_invitations.py
  src/backend/pyproject.toml
Labels: noChangeLog, backend, V1

#139 🐛(helm) fix wrongly named ingress
  src/helm/env.d/dev/values.desk.yaml.gotmpl
  src/helm/env.d/staging/values.desk.yaml.gotmpl
Labels: bug, noChangeLog

#140 🧑‍💻(frontend) remove CI control on traduction frontend
  .github/workflows/people.yml
Labels: enhancement, noChangeLog, easy pick

#146 🔧(renovate) open Renovate PR with a default noChangeLog label
  renovate.json
Labels: noChangeLog

#155 🚑️(staging) fix 404 errors
  src/helm/env.d/staging/values.desk.yaml.gotmpl
Labels: bug, noChangeLog

#152 [CI] Call argocd webhook after the push of new image on staging
  .github/workflows/docker-hub.yml
  .github/workflows/secrets.enc.env
Labels: noChangeLog

#157 [CI] Transform migrate job to Presync job
  src/helm/desk/templates/backend_job.yaml
  src/helm/desk/values.yaml
  src/helm/env.d/staging/values.desk.yaml.gotmpl
Labels: noChangeLog

#126 Enable sorting on columns
  src/frontend/apps/desk/src/features/members/__tests__/MemberGrid.test.tsx
  src/frontend/apps/desk/src/features/members/api/useTeamsAccesses.tsx
  src/frontend/apps/desk/src/features/members/components/MemberGrid.tsx
Labels: noChangeLog

#158 🚧(frontend) add applications menu PoC
  src/frontend/apps/desk/src/features/header/ApplicationsMenu.tsx
  src/frontend/apps/desk/src/features/header/Header.tsx
  src/frontend/apps/e2e/__tests__/app-desk/header.spec.ts
Labels: noChangeLog

#166 🚨(app-desk) remove warning next.js about css from Head
  src/frontend/apps/desk/src/features/header/ApplicationsMenu.tsx
  src/frontend/apps/desk/src/pages/_document.tsx
Labels: frontend, noChangeLog
