Repository suitenumerique/people, pull requests merged in 2025-01, with the labels that each got.

#627 🐛(tests) fix flaky back-end test
  src/backend/core/tests/contacts/test_core_api_contacts_list.py
Labels: noChangeLog, backend

#629 🧑‍💻(admin) add filter for domain
  src/backend/mailbox_manager/admin.py
Labels: noChangeLog

#632 🧑‍💻(admin) add read-only fields to mailbox admin
  src/backend/mailbox_manager/admin.py
Labels: noChangeLog, backend

#642 ♻️ (tests) reorganization of test files
  src/backend/mailbox_manager/tests/commands/test_dimail_setup_db.py
  src/backend/mailbox_manager/tests/models/test_mailboxes.py
  src/backend/mailbox_manager/tests/models/test_maildomain.py
  src/backend/mailbox_manager/tests/models/test_maildomainaccess.py
Labels: noChangeLog

#643 ✅(dimail) improve fetch domain status tests
  src/backend/mailbox_manager/tests/fixtures/dimail.py
  src/backend/mailbox_manager/tests/test_admin_actions.py
  src/backend/mailbox_manager/tests/test_utils_dimail_client.py
Labels: noChangeLog

#615 🧑‍💻(dimail) add missing John Doe access role on domain
  src/backend/mailbox_manager/management/commands/setup_dimail_db.py
  src/backend/mailbox_manager/tests/commands/test_dimail_setup_db.py
Labels: noChangeLog

#648 🐛(tilt) add missing file after previous commit
  bin/install-external-secrets.sh
Labels: noChangeLog

#649 ✨(api) create stats endpoint
  CHANGELOG.md
  src/backend/core/api/client/viewsets.py
  src/backend/core/tests/test_api_stats.py
  src/backend/people/api_urls.py
Labels: backend

#653 🐛(ci) fix argocd webhook to auto deploy on staging
  .github/workflows/docker-hub.yml
Labels: noChangeLog

#656 🔖(minor) release version 1.10.0
  CHANGELOG.md
  src/backend/pyproject.toml
  src/frontend/apps/desk/package.json
  src/frontend/apps/e2e/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-people/package.json
  src/frontend/packages/i18n/package.json
Labels: release

#657 Mise à jour du script de release
  CHANGELOG.md
  scripts/release.py
Labels: backend

#659 🐛(dimail) fix imported mailboxes should be enabled instead of pending
  CHANGELOG.md
  src/backend/mailbox_manager/tests/test_utils_dimail_client.py
  src/backend/mailbox_manager/utils/dimail.py
Labels: backend, easy pick, dimail

#666 ✨(scripts) improve release script
  scripts/release.py
Labels: noChangeLog
