Repository suitenumerique/people, pull requests merged in 2025-02, with the labels that each got.

#677 🧑‍💻(tilt) add mailcatcher to the stack
  src/helm/env.d/dev/values.desk.yaml.gotmpl
  src/helm/helmfile.yaml
  src/helm/mailcatcher/Chart.yaml
  src/helm/mailcatcher/templates/deployment.yaml
  src/helm/mailcatcher/templates/ingress.yaml
  src/helm/mailcatcher/templates/service.yaml
  src/helm/mailcatcher/values.yaml
Labels: noChangeLog

#681 🌐(backend) add missing translations
  src/backend/core/models.py
  src/backend/core/tests/test_models_invitations.py
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/mail/mjml/invitation.mjml
Labels: noChangeLog

#702 🚚(github) update all mentions to github repo
  .github/ISSUE_TEMPLATE/Support_question.md
  CHANGELOG.md
  src/backend/core/authentication/backends.py
  src/backend/pyproject.toml
  src/frontend/apps/desk/src/components/Modal.tsx
  src/frontend/apps/desk/src/features/language/LanguagePicker.tsx
  src/mail/package.json
  src/tsclient/package.json
Labels: noChangeLog

#704 🌐(backend) add missing translations
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
Labels: noChangeLog

#707 🔧(helm) add pdbs to deployments
  src/helm/desk/Chart.yaml
  src/helm/desk/README.md
  src/helm/desk/templates/backend_deployment.yaml
  src/helm/desk/templates/frontend_deployment.yaml
  src/helm/desk/values.yaml
Labels: noChangeLog

#712 🐛(plugin) fix support email
  src/backend/plugins/organizations.py
Labels: noChangeLog

#717 🧑‍💻(domains) change default ordering
  src/backend/mailbox_manager/models.py
  src/backend/mailbox_manager/tests/test_utils_dimail_client.py
Labels: noChangeLog

#719 :loud_sound:(prod) move logging config up to Base configuration class
  src/backend/people/settings.py
Labels: noChangeLog

#721 💄(frontend) change support email example
  src/frontend/apps/desk/src/features/mail-domains/domains/components/ModalAddMailDomain.tsx
  src/frontend/apps/desk/src/i18n/translations.json
Labels: noChangeLog

#724 🔒️(docker) patch libssl3 and libcrypto3 to address CVE-2024-12797
  Dockerfile
Labels: noChangeLog

#730 🩹(domains) add missing migrations after define ordering
  src/backend/mailbox_manager/migrations/0020_alter_mailbox_options_alter_maildomain_options_and_more.py
Labels: noChangeLog

#731 ⚡️(ci) save time on CI by not downloading already present browser
  .github/workflows/people.yml
  src/frontend/apps/e2e/playwright.config.ts
Labels: noChangeLog

#736 🐛(communes) add missing user creation and status in domain provisioning
  src/backend/plugins/organizations.py
  src/backend/plugins/tests/organizations/test_commune_creation.py
  src/frontend/apps/e2e/__tests__/app-desk/domain-provisioning.spec.ts
Labels: noChangeLog

#689 📝(tilt) improve tilt doc
  docs/local_development_kube.md
Labels: noChangeLog

#726 🌐(backend) use again crowdin for translations
  CHANGELOG.md
  src/backend/core/tests/test_models_invitations.py
  src/backend/locale/en_US/LC_MESSAGES/django.mo
  src/backend/locale/en_US/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
Labels: noChangeLog

#743 🧱(helm) add `resource-server` ingress path
  CHANGELOG.md
  src/helm/desk/Chart.yaml
  src/helm/desk/templates/ingress.yaml
Labels: helm

#744 🧑‍💻(scripts) improve release script
  scripts/release.py
Labels: noChangeLog

#738 🧑‍💻(bootstrap) install playwright browsers for local dev
  Makefile
Labels: noChangeLog

#737 📌(renovate) ignore @hookform/resolvers until issue fixed
  renovate.json
Labels: noChangeLog

#729 🔧(swagger) activate swagger in staging
  src/backend/core/tests/swagger/test_openapi_schema.py
  src/backend/people/settings.py
Labels: noChangeLog, backend

#749 🔧(api) allow swagger collection
  src/backend/people/settings.py
  src/backend/pyproject.toml
Labels: noChangeLog
